extends:
  - 'spectral:oas'
  - 'spectral:asyncapi'
  - 'spectral:arazzo'
  - 'spectral-aws-apigateway-ruleset'

overrides:
  - files:
      - 'dist/spec.rendered.yaml'
    rules:
      # Disabling these rules for OPTIONS methods
      operation-description:
        given: '$.paths[*].options'
        then:
          function: truthy
        severity: off
      operation-tags:
        given: '$.paths[*].options'
        then:
          function: truthy
        severity: off
      operation-operationId:
        given: '$.paths[*].options'
        then:
          function: truthy
        severity: off
      # The example tag is not supported by API gateway, but there is no harm in including it
      aws-example-tag:
        given: '$.*'
        then:
          function: truthy
        severity: off
      # Format not supported by JSONSchema4, therefore may be ignored
      aws-supported-formats:
        given: '$.*'
        then:
          function: truthy
        severity: off
