---
openapi: '3.0.1'
info:
  title: Payments
paths:
  /api/v1/payment-session:
    post:
      summary: Create payment session with vendor
      operationId: paymentSession
      description: Creates payment session with vendor
      tags: [payments]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Request payload with tier/topup and language. Must include either tier or topup, but not both. Ideally, the schema would use `oneOf`, but AWS APIGW has selective support for it.
              properties:
                tier: { $ref: './component-definitions.yaml#/components/schemas/Tier' }
                topup: { $ref: './component-definitions.yaml#/components/schemas/Topup' }
                language: { $ref: './component-definitions.yaml#/components/schemas/LanguageCode' }
              required: [language]
              additionalProperties: false
      responses:
        '200': { $ref: './component-definitions.yaml#/components/responses/PaymentSessionResult' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '409': { $ref: './component-definitions.yaml#/components/responses/Conflict' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.post_payment_session_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/customer-portal-session:
    post:
      summary: Create customer portal session with vendor
      operationId: customerPortalSession
      description: Creates customer portal session with vendor
      tags: [payments]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              description: Request payload containing customer portal session config
              properties:
                flowType:
                  description: Type of flow for the customer portal session.
                  type: string
                  enum: ['subscription_cancel', 'subscription_update', 'payment_method_update']
              additionalProperties: false
      responses:
        '200':
          { $ref: './component-definitions.yaml#/components/responses/CustomerPortalSessionResult' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.post_customer_portal_session_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'
