---
openapi: '3.0.1'
info:
  title: Notifycal API
  description: Notifycal API
  contact:
    name: Notifycal CTO
    url: https://github.com/notifycal
    email: notifycal@gmail.com
  version: ${version}
# API GW Ignores this (surpriiiise!)
servers:
  - url: https://api{environment}.notifycal.com/api/{api_version}
    variables:
      environment:
        default: ''
        enum:
          - '' # Production
          - .qa # QA server
          - .dev # Development
      api_version:
        default: v1
        enum:
          - v1

paths:
  /api/v1/login:
    post:
      summary: Login endpoint
      operationId: login
      tags: [user, auth]
      description: Let a user login against environment APIs
      parameters:
        - name: idp
          in: query
          description: The Idp verification mechanism to be used
          required: true
          schema:
            type: string
            default: google.com
            enum:
              - google.com
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Request payload containing google code provided by Google to the user on successful oauth logon
              properties:
                googleCode:
                  description: code to verify against Google to check that user is who they claim they are
                  type: string
      security: [] # This overrides global definition since this endpoint is unprotected
      responses:
        '200': { $ref: './component-definitions.yaml#/components/responses/AuthenticationOK' }
        '400': { $ref: './component-definitions.yaml#/components/responses/BadRequest' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.post_login_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/refresh:
    post:
      summary: Refresh endpoint
      operationId: refresh
      tags: [user, auth]
      description: Let a user regenerate authentication against environment APIs using a refresh token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Request payload containing refresh token
              properties:
                refreshToken:
                  description: token provided by system APIs to refresh authorization
                  type: string
      security: [] # This overrides global definition since this endpoint is unprotected
      responses:
        '200': { $ref: './component-definitions.yaml#/components/responses/AuthenticationOK' }
        '400': { $ref: './component-definitions.yaml#/components/responses/BadRequest' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '403': { $ref: './component-definitions.yaml#/components/responses/Forbidden' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.post_refresh_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/user-profile:
    get:
      summary: Get user profile
      operationId: getUserProfile
      description: Returns the user profile of the caller
      tags: [user]
      responses:
        '200': { $ref: './component-definitions.yaml#/components/responses/UserProfile' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '404': { $ref: './component-definitions.yaml#/components/responses/NotFound' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.get_user_profile_arn}/invocations'
    patch:
      summary: Patch User profile
      operationId: patchUserProfile
      description: Updates the user profile of the caller
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: './component-definitions.yaml#/components/schemas/ReminderConfig'
      responses:
        '204': { $ref: './component-definitions.yaml#/components/responses/Response204' }
        '400': { $ref: './component-definitions.yaml#/components/responses/BadRequest' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.patch_user_profile_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/idp/user-calendars:
    get:
      summary: User calendar list from Idp
      operationId: userCalendarListFromIdp
      description: Returns the user calendar list of the caller from idp
      tags: [user, idp-proxy]
      responses:
        '200': { $ref: './component-definitions.yaml#/components/responses/UserIdpCalendars' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.get_idp_user_calendars_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/demo-reminder:
    post:
      summary: Post Demo Reminder
      operationId: postDemoReminder
      description: Send an inmediate demo reminder to the user
      tags: [user, messaging, demo]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Request payload containing demo reminder config
              properties:
                receiverContact:
                  $ref: './component-definitions.yaml#/components/schemas/ReceiverContact'
                startTime:
                  $ref: './component-definitions.yaml#/components/schemas/DateTime'
              additionalProperties: true
      responses:
        '202': { $ref: './component-definitions.yaml#/components/responses/Response202' }
        '400': { $ref: './component-definitions.yaml#/components/responses/BadRequest' }
        '401': { $ref: './component-definitions.yaml#/components/responses/Unauthorised' }
        '500': { $ref: './component-definitions.yaml#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.post_demo_reminder_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/webhook/reminder-status:
    $ref: './messaging-webhook-vonage.yaml#/paths/~1api~1v1~1webhook~1reminder-status'

  /api/v1/payment-session:
    $ref: './payments-stripe.yaml#/paths/~1api~1v1~1payment-session'

  /api/v1/customer-portal-session:
    $ref: './payments-stripe.yaml#/paths/~1api~1v1~1customer-portal-session'

tags:
  - name: user
    description: user operations
  - name: idp-proxy
    description: idp proxy operations
  - name: auth
    description: authentication operations
  - name: webhook
    description: webhooks
  - name: messaging
    description: integration with messaging provider
  - name: payments
    description: integration with payment provider
  - name: demo
    description: demo operations
