---
openapi: '3.0.1'
info:
  title: Notifycal API
  description: Notifycal API
  contact:
    name: Notifycal CTO
    url: https://github.com/notifycal
    email: notifycal@gmail.com
  version: ${version}
# API GW Ignores this (surpriiiise!)
servers:
  - url: https://api{environment}.notifycal.com/api/{api_version}
    variables:
      environment:
        default: ''
        enum:
          - '' # Production
          - .qa # QA server
          - .dev # Development
      api_version:
        default: v1
        enum:
          - v1

x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'${cors_origin}'"
      gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS,PUT,DELETE,PATCH'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
    responseTemplates:
      application/json: '{"message":"Client Error"}'
    statusCode: 400

  DEFAULT_5XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Origin: "'${cors_origin}'"
      gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS,PUT,DELETE,PATCH'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
    responseTemplates:
      application/json: '{"message":"Server Error"}'
    statusCode: 500

paths:
  /api/v1/login:
    post:
      summary: Login endpoint
      operationId: login
      tags: [user, auth]
      description: Let a user login against environment APIs
      parameters:
        - name: idp
          in: query
          description: The Idp verification mechanism to be used
          required: true
          schema:
            type: string
            default: google.com
            enum:
              - google.com
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Request payload containing google code provided by Google to the user on successful oauth logon
              properties:
                googleCode:
                  description: code to verify against Google to check that user is who they claim they are
                  type: string
      security: [] # This overrides global definition since this endpoint is unprotected
      responses:
        '200': { $ref: '#/components/responses/AuthenticationOK' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorised' }
        '500': { $ref: '#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.post_login_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/refresh:
    post:
      summary: Refresh endpoint
      operationId: refresh
      tags: [user, auth]
      description: Let a user regenerate authentication against environment APIs using a refresh token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Request payload containing refresh token
              properties:
                refreshToken:
                  description: token provided by system APIs to refresh authorization
                  type: string
      security: [] # This overrides global definition since this endpoint is unprotected
      responses:
        '200': { $ref: '#/components/responses/AuthenticationOK' }
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorised' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '500': { $ref: '#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.post_refresh_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/user-profile:
    get:
      summary: Get user profile
      operationId: getUserProfile
      description: Returns the user profile of the caller
      tags: [user]
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: { $ref: '#/components/schemas/User' }
                required: [result]
                additionalProperties: false
        '401': { $ref: '#/components/responses/Unauthorised' }
        '404': { $ref: '#/components/responses/NotFound' }
        '500': { $ref: '#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.get_user_profile_arn}/invocations'
    patch:
      summary: Patch User profile
      operationId: patchUserProfile
      description: Updates the user profile of the caller
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Request payload containing reminder config
              properties:
                businessName:
                  description: Business name
                  type: string
                businessAddress:
                  description: Business address
                  type: string
                calendars:
                  $ref: '#/components/schemas/CalendarList'
      responses:
        '204':
          description: 'No Content'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorised' }
        '500': { $ref: '#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.patch_user_profile_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

  /api/v1/idp/user-calendars:
    get:
      summary: User calendar list from Idp
      operationId: userCalendarListFromIdp
      description: Returns the user calendar list of the caller from idp
      tags: [user, idp-proxy]
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  result: { $ref: '#/components/schemas/CalendarList' }
                required: [result]
                additionalProperties: false
        '401': { $ref: '#/components/responses/Unauthorised' }
        '500': { $ref: '#/components/responses/InternalServerError' }
      x-amazon-apigateway-integration:
        $ref: './aws-stuff.yaml#/components/x-notifycal/AWS_LAMBDA_PROXY'
        uri: 'arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_functions.get_idp_user_calendars_arn}/invocations'
    options:
      $ref: './aws-stuff.yaml#/components/x-notifycal/CORS_OPTIONS'

components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        idp:
          type: string
        idpId:
          type: string
        lastSignInAt:
          $ref: '#/components/schemas/UnixTimestamp'
        signedUpAt:
          $ref: '#/components/schemas/UnixTimestamp'
        userStatus:
          type: string
          enum:
            - live
            - onboarding
            - banned
      required:
        - userId
        - email
        - idp
        - idpId
        - lastSignInAt
        - signedUpAt
        - userStatus
      # Additionalproperties are allowed by default in OpenAPI. To enforce maximum strictness use additionalProperties: false to block all arbitrary data.
      additionalProperties: false

    CalendarList:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
        required:
          - id
          - name
        # Additionalproperties are allowed by default in OpenAPI. To enforce maximum strictness use additionalProperties: false to block all arbitrary data.
        additionalProperties: false

    UnixTimestamp:
      type: number
      format: int64
      description: Unix timestamp in seconds

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          # This will limit us in case we want to send dynamic/custom error messages. But it's ok for now
          enum:
            - Bad Request
            - Unauthorised
            - Not Found
            - Forbidden
            - KO
      required:
        - message
      additionalProperties: false

  responses:
    AuthenticationOK:
      description: OK
      content:
        application/json:
          schema:
            type: object
            description: Response payload containing authorization
            properties:
              accessToken:
                description: jwt to use as an authorization against all system APIs. It contains the following claims userId, email, idp and idpId
                type: string
              tokenType:
                type: string
                enum:
                  - Bearer
              refreshToken:
                description: jwt to refresh authorization for system APIs
                type: string
            required:
              - accessToken
              - tokenType
              - refreshToken

    BadRequest:
      description: Bad Request response payload
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }

    Unauthorised:
      description: Unauthorised response payload
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }

    Forbidden:
      description: Forbidden response payload
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }

    NotFound:
      description: NotFound response payload
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }

    InternalServerError:
      description: Internal Server Error response payload
      content:
        application/json:
          schema: { $ref: '#/components/schemas/ErrorResponse' }

    CORSResponse:
      description: CORS Preflight Response
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
        Access-Control-Allow-Methods:
          schema:
            type: string
        Access-Control-Allow-Headers:
          schema:
            type: string
        Access-Control-Max-Age:
          schema:
            type: integer
            example: 86400

tags:
  - name: user
    description: user operations
  - name: idp-proxy
    description: idp proxy operations
  - name: auth
    description: authentication operations
